// Code generated by protoc-gen-go.
// source: datastructure.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	datastructure.proto
	service.proto

It has these top-level messages:
	DataStructure
	Service
	Section
	Method
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type DataStructure struct {
	Raw string `protobuf:"bytes,1,opt,name=Raw,json=raw" json:"Raw,omitempty"`
}

func (m *DataStructure) Reset()                    { *m = DataStructure{} }
func (m *DataStructure) String() string            { return proto.CompactTextString(m) }
func (*DataStructure) ProtoMessage()               {}
func (*DataStructure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*DataStructure)(nil), "model.DataStructure")
}

var fileDescriptor0 = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x49, 0x2c, 0x49,
	0x2c, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x29, 0x2d, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x52, 0xe4, 0xe2, 0x75, 0x01, 0xca, 0x06, 0xc3, 0x64,
	0x85, 0x04, 0xb8, 0x98, 0x83, 0x12, 0xcb, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x8b,
	0x12, 0xcb, 0x93, 0xd8, 0xc0, 0x1a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x17, 0x1d, 0x5e,
	0xda, 0x47, 0x00, 0x00, 0x00,
}
